import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { utopiaStd, spaceGrotesk } from "@/app/utils/fonts";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${utopiaStd.variable} ${spaceGrotesk.variable}`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
